name: clib_serialport_dart
description: A dart wrapper for clibserialport
repository: https://github.com/BR4YD3N-G/clib_serialport_dart
version: 1.1.0

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  crypto: ^3.0.2
  path: ^1.8.2
